### PR TITLE
Bump version to 1.90.7

### PR DESCRIPTION
**Pull request by wroyca**
Bump version to 1.90.7

https://github.com/ocornut/imgui/releases/tag/v1.90.7

### CODE REVIEW

**Review by Rookfighter — COMMENTED** [review]
Changes look alright, any idea why the windows MSVC builds fail?

**Comment by Klaim** [comment]
@Rookfighter See 
- https://github.com/build2-packaging/glfw/issues/10
- https://github.com/build2-packaging/glfw/pull/11

So it *should* be fixed once glfw is fixed and it's package revision is published.

**Review by Rookfighter — APPROVED** [review]
Expecting the failed builds to be fixed with fixes of GLFW

**Comment by wroyca** [comment]
@Rookfighter The new GLFW revision is now available in stable, and all ImGui tests now pass properly :tada:

**Review by Rookfighter — APPROVED** [review]
Thanks for fixing the GLFW package. Looks all good to me, CI is also happy :+1:

**Pull request merged**
