### PR TITLE
Bump version to 1.90.6

### PR DESCRIPTION
**Pull request by wroyca**
Nothing much to say here, this is just the usual version bump. ☕

### CODE REVIEW

**Comment by wroyca** [comment]
Failure with Ubuntu (clang) is due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110970. Already fixed upstream but CI is a little behind.

**Comment by wroyca** [comment]
soft ping @Rookfighter @boris-kolpackov to know if Ubuntu (clang) CI failing due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110970 is something you considers blocking / problematic. :pray:

**Comment by Rookfighter** [comment]
I think this is acceptable. The Ubuntu runners are configured as latest, so as soon as latest is moved to Ubuntu 24.04 the problem should be gone anyway.
IMO the GitHub Actions just act as simple smoke test. since most of them succeed and the failure reason of the others is known, I think there is no need to invest any time in fixing the build right now.

**Comment by wroyca** [comment]
> I think this is acceptable. The Ubuntu runners are configured as latest, so as soon as latest is moved to Ubuntu 24.04 the problem should be gone anyway. IMO the GitHub Actions just act as simple smoke test. since most of them succeed and the failure reason of the others is known, I think there is no need to invest any time in fixing the build right now.

Sweet! I also see that boris also reacted with a thumb up, so that PR is good to go on my side, one thing is that I don't own a mac to test locally, so I'll have to trust the CI here; in any case, let me know if I missed anything :+1:

**Review by Rookfighter — APPROVED** [review]

**Comment by wroyca** [comment]
Soft ping, @Rookfighter, was there a chance publishing the revision slipped your mind? No pressure if time didn't permit—just checking in! :)

**Pull request merged**
