### PR TITLE
Prepare for cppget.org

### PR DESCRIPTION
**Pull request by Rookfighter**
`libopengl-meta` and `libvulkan-meta` are now published on cppget.org (testing). This PR fixes the last remaining issues before publishing imgui. This includes

* add lib prefix to `imgui-examples`
* fix conditional build dependency graph

bdep ci results can be found here:https://ci.cppget.org/@9f55a275-d712-40d8-bdf4-e51294ef1ecc

@Swat-SomeBug Do you want to take care of publishing to cppget.org (since its your repository)? Or should I do it?

@boris-kolpackov A few open points worth a discussion:

* the top level buildfile has conditional build rules. Since it is a repo "glue" file (not part of a package), is that ok or do I have to fix it?
* the package `libimgui-examples` currently does not build any macos examples (there is a outcommented line in the buildfile) as nobody has cared to cast another objective C spell on those buildfiles. Is that a game breaker for publishing on cppget.org?
* in the bdep ci link above, there are no builds of `libimgui-examples` although it was listed on the command line when I executed `bdep ci`. What's the reason behind this?

### CODE REVIEW

**Comment by boris-kolpackov** [comment]
> the top level buildfile has conditional build rules. Since it is a repo "glue" file (not part of a package), is that ok or do I have to fix it?

Yes, the current implementation is at best an "approximation" (the C++ compiler that it "sees" may not match the one used by the packages). My suggestion is to just remove it. The glue `buildfile` works reasonably well for simple repositories with a uniform set of package but once thing start to become conditional (or split into host/target), then it becomes more of a liability. At least that's what we've been doing in our own projects (for example, in build system modules).

> the package libimgui-examples currently does not build any macos examples (there is a outcommented line in the buildfile) as nobody has cared to cast another objective C spell on those buildfiles. Is that a game breaker for publishing on cppget.org?

No, that's fine. Also, I am planning to look into supporting Objective-C/C++ compilation as part of the `cc` module so hopefully once this is available, it will be easier to improve.

> in the `bdep ci` link above, there are no builds of `libimgui-examples` although it was listed on the command line when I executed `bdep ci`. What's the reason behind this?

That's because you have listed it as `examples: ` in `libimgui/manifest` (which is the right thing to do). Because of that `libimgui-examples` is built/tested as part of `libimgui` (in a sense, it is treated as a separate tests package for `libimgui`). You can confirm this by grepping the logs, for example: https://ci.cppget.org/@9f55a275-d712-40d8-bdf4-e51294ef1ecc/libimgui/1.86.0-a.0.20220906183917.799d713eab78/log/linux_debian_11-clang_13.0/public/0.15.0

**Review by boris-kolpackov — APPROVED** [review]
LGTM

**Comment by boris-kolpackov** [comment]
BTW, regarding the `imgui-examples` to `libimgui-examples` rename, as you may remember, it used to be called `libimgui-examples` and it was me who suggested that we rename it to `imgui-examples`. But after some more thinking/perspective, I now believe the `libimgui-examples` is the correct name (for details, see https://github.com/build2-packaging/libopengl-meta/issues/2#issuecomment-1234550322). Sorry for the churn.

**Comment by Rookfighter** [comment]
Alright thanks for the feedback. I think the glue file is needed for the GitHub Workflows right now, since they cannot parse the `builds` parts of manifest files. So if the glue file does not do any harm right now, I would leave it in place. Maybe in the future I can extend the Workflows to respect the manifests

**Comment by boris-kolpackov** [comment]
> So if the glue file does not do any harm right now, I would leave it in place.

I ruminated a bit more on this and I think it can actually be fixed into something sensible without too much effort. I've filed an issue with the details: https://github.com/build2-packaging/imgui/issues/13

**Pull request merged**
